use clickhouse::Row;
use serde::{Deserialize, Serialize};

/// A single RUM event from the rum_events table.
#[derive(Debug, Clone, Serialize, Deserialize, Row)]
pub struct RumRecord {
    #[serde(rename = "Timestamp")]
    pub timestamp: i64,
    #[serde(rename = "AppName")]
    pub app_name: String,
    #[serde(rename = "AppVersion")]
    pub app_version: String,
    #[serde(rename = "Environment")]
    pub environment: String,
    #[serde(rename = "SessionId")]
    pub session_id: String,
    #[serde(rename = "UserId")]
    pub user_id: String,
    #[serde(rename = "PageUrl")]
    pub page_url: String,
    #[serde(rename = "PagePath")]
    pub page_path: String,
    #[serde(rename = "ViewName")]
    pub view_name: String,
    #[serde(rename = "Referrer")]
    pub referrer: String,
    #[serde(rename = "BrowserName")]
    pub browser_name: String,
    #[serde(rename = "BrowserVersion")]
    pub browser_version: String,
    #[serde(rename = "OsName")]
    pub os_name: String,
    #[serde(rename = "OsVersion")]
    pub os_version: String,
    #[serde(rename = "DeviceType")]
    pub device_type: String,
    #[serde(rename = "ScreenWidth")]
    pub screen_width: u16,
    #[serde(rename = "ScreenHeight")]
    pub screen_height: u16,
    #[serde(rename = "EventType")]
    pub event_type: String,
    #[serde(rename = "EventName")]
    pub event_name: String,
    #[serde(rename = "VitalName")]
    pub vital_name: String,
    #[serde(rename = "VitalValue")]
    pub vital_value: f64,
    #[serde(rename = "VitalRating")]
    pub vital_rating: String,
    #[serde(rename = "ErrorMessage")]
    pub error_message: String,
    #[serde(rename = "ErrorStack")]
    pub error_stack: String,
    #[serde(rename = "ErrorType")]
    pub error_type: String,
    #[serde(rename = "InteractionTarget")]
    pub interaction_target: String,
    #[serde(rename = "InteractionType")]
    pub interaction_type: String,
    #[serde(rename = "DurationMs")]
    pub duration_ms: f64,
    #[serde(rename = "TraceId")]
    pub trace_id: String,
    #[serde(rename = "SpanId")]
    pub span_id: String,
    #[serde(rename = "Attributes")]
    pub attributes: String,
}
